function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(9)=1;
    ys_(7)=1/params(2)-(1-params(3));
    ys_(8)=(1-params(1))*(params(1)/ys_(7))^(params(1)/(1-params(1)));
    ys_(1)=ys_(8)*params(4)/params(5)/(1+(1-params(1))*params(4)/params(5)-params(3)*params(1)/ys_(7));
    ys_(2)=params(4)/params(5)*(ys_(8)-(1-params(1))*ys_(1));
    ys_(3)=params(3)*params(1)*ys_(1)/ys_(7);
    ys_(6)=params(1)*ys_(1)/ys_(7);
    ys_(4)=(1-params(1))*ys_(1)/ys_(8);
    ys_(5)=1-ys_(4);
    % Auxiliary equations
end
